### PR TITLE
Lift the 2 characters restriction

### PR DESCRIPTION
**Pull request by MichaelBitard**
Hi,

I took over this PR: https://github.com/entwicklerstube/babel-plugin-root-import/pull/116 because we need it, I hope you don't mind.

### CODE REVIEW

**Comment by brigand** [comment]
Thanks for the PR.

Couldn't we just use `.indexOf(rootPathPrefix) === 0` instead of the dependency and going through RegExp?

**Comment by MichaelBitard** [comment]
Wow, you are absolutely right!

**Comment by MichaelBitard** [comment]
There, should be better

**Comment by MichaelBitard** [comment]
Thanks!

**Comment by brigand** [comment]
Appreciate you doing this. Published as 6.2.0

**Pull request merged**
