### PR TITLE
Check prefix more carefully

### LINKED ISSUE #96: Cannot import scoped package
I use the following config:
```
        ["root-import", {
            "rootPathSuffix": "src",
            "rootPathPrefix": "@"
        }]
```

In this configuration I cannot import scoped packages, because the plugin replaces paths.

### PR DESCRIPTION
**Pull request by loyd**
Fixes #96.

### CODE REVIEW

**Comment by loyd** [comment]
@michaelzoidl bump )

**Comment by rmkpatchaa** [comment]
Any chance to have this merged soon ?

**Comment by dowgsss** [comment]
something?

**Comment by GoPro16** [comment]
This going to be merged at all? I will fork and release under a different scope.

**Comment by brigand** [comment]
@GoPro16 I think we should properly handle the prefix being provided as `"@/"` in the config instead. If you could send a PR for that, that'd be very much appreciated.

**Pull request closed without merging**
