### PR TITLE
Add babel 7+ support fix

### LINKED ISSUE #92: Incompatible with babel 7
Babel 7 drops support for arrays as the root value for a plugin's options. This means when using babel 7+ multiple aliases cannot be used

### PR DESCRIPTION
**Pull request by vihanb**
Fixes #92 and #78 
Signed-off-by: Vihan <contact@vihan.org>

### CODE REVIEW

**Comment by tomspeak** [comment]
+1 would love this feature to be merged.

**Comment by michaelzoidl** [comment]
Hey thanks for the PR :) 
Can we keep both examples in the README? Each one with a headline e.g. `Babel v6` and yours with the headline `Babel v7`?

Thanks for the contribution ✌️

**Comment by loyd** [comment]
Bump )

**Comment by Hoten** [comment]
Can this be merged?

**Comment by billnbell** [comment]
@michaelzoidl Please approve

**Comment by michaelzoidl** [comment]
Hey @vihanb,

thanks for contributing and sorry for the delay. Ok looks good, would it be possible to revert the renaming of the name in the package.json? :) 

Also, seems there is a little conflict in the README (we've updated some things) could you resolve them?

Thanks.

Btw.. I'am searching for help in this project checkout #104

**Comment by vihanb** [comment]
@michaelzoidl sorry for late response, i have fixed conflict + package.json

**Comment by brigand** [comment]
@vihanb thanks!

**Pull request merged**
